create table tUser
             (
             UserID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
             Name varchar(50),
             Pass varchar(50),
             Mail varchar(255)
             );

create table tAudit
             (
             AuditID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
             UserID int REFERENCES tUser (UserID),
             ActionType smallint,  /* 1 - Registration, 2 - CheckMail, 3 - LogInPass, 4 - LogOut, 5 - LoginFail*/
             ActionDate timestamp
             );

create table tAccessToken
             (
             TokenID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
             AuditID int REFERENCES tAudit (AuditID),
             UserID  int REFERENCES tUser (UserID),
             ExpireDate timestamp
             );